config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'restaurants#index'
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
 CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]

  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
 before_action :set_rest, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def edit; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(rest_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end

  end


 private

  def rest_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number, :rating)
  end

  def set_rest
    @restaurant = Restaurant.find(params[:id])
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    # we need @restaurant in our `simple_form_for`
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end


  def create
    @review = Review.create(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
  <!-- Add these line for detecting device width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <!-- [...] -->
</head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |t| %>
    <%= t.input :name %>
    <%= t.input :address %>
    <%= t.input :category%>
    <%= t.input :phone_number %>
    <%= t.submit %>
  <% end %>
</div>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>
  <p><%= link_to restaurant.name, restaurant_path(restaurant.id) %></p>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.category %></p>
<% end %>

<%= link_to 'add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container">
  <%= simple_form_for(@restaurant) do |t| %>
    <%= t.input :name %>
    <%= t.input :address %>
    <%= t.input :category%>
    <%= t.input :phone_number %>
    <%= t.submit %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category%></p>

<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">Description: <%= review.content %></li>
     <li class="list-group-item">Rating: <%= review.rating %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %> |
<%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>